apiVersion: apps/v1
kind: Deployment
metadata:
  name: temptool
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: temptool
  template:
    metadata:
      labels:
        deployment: temptool
    spec:
      containers:
      - name: temptool
        image: gcr.io/temptool/temptool
        env:
          - name: FIRESTORE_KEY
            valueFrom:
              secretKeyRef:
                name: firestore-key
                key: FIRESTORE_KEY
                optional: false
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-key
                key: JWT_SECRET_KEY
                optional: false
          - name: MJ_APIKEY_PRIVATE
            valueFrom:
              secretKeyRef:
                name: mj-apikey-private
                key: MJ_APIKEY_PRIVATE
                optional: false
          - name: MJ_APIKEY_PUBLIC
            valueFrom:
              secretKeyRef:
                name: mj-apikey-public
                key: MJ_APIKEY_PUBLIC
                optional: false
        ports:
        - containerPort: 80
