apiVersion: apps/v1
kind: Deployment
metadata:
  name: temptool
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: temptool
  template:
    metadata:
      labels:
        deployment: temptool
    spec:
      containers:
      - name: temptool
        image: gcr.io/temptool/temptool
        env:
          - name: FIRESTORE_KEY
            valueFrom:
              secretKeyRef:
                name: firestore-key
                key: FIRESTORE_KEY
                optional: false
        ports:
        - containerPort: 80
