# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Lint

on:
  push:
    paths:
    - 'Server/**'
  pull_request:
    paths:
    - 'Server/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle pytest
        if [ -f Server/requirements.txt ]; then pip install -r Server/requirements.txt; fi
    - name: Lint with pycodestyle
      run: |
        pycodestyle Server --max-line-length 127 --statistics
